tgz as plain_text
qiita-spots/qtp-biom pull request #26
Opened 2023-08-09 15:56 UTC by antgonza

2023-08-10 10:18 UTC, antgonza commented
@charles-cowart, this was already deployed in qiita-rc and is working as expected.

2023-08-16 17:36 UTC, charles-cowart requested changes
Everything looks good - just need confirmation on one thing.

2023-08-16 17:36 UTC, charles-cowart commented on qtp_biom/validate.py
> +            filepaths.append((filename, 'plain_text'))
Is it okay that we're appending 'plain_text' along with a path to a tarball in this list? It's not clear to me whether the 'plain_text' is a reference to the file's uncompressed contents or the file itself. I'm concerned that the user of this list will have to know to exists() each filename to test if it's a tarball and process accordingly.

2023-08-16 17:58 UTC, charles-cowart commented on qtp_biom/validate.py
> +            filepaths.append((filename, 'plain_text'))
Approved. This was discussed in qiita-admin.

2023-08-16 17:58 UTC, merged